name: Auto Add Project

on:
  issues:
    types:
      - opened
      - reopened
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review

permissions:
  issues: write

jobs:
  add-to-project:
    name: Add To GitHub projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/jv-kune-kune/projects/1
          github-token: ${{ secrets.PAT_SECRET }}
      - name: Set Output for Resource URL
        id: set-output
        run: |
          echo "::set-output name=resource_url::${{ github.event.issue.html_url || github.event.pull_request.html_url }}"
