name: Auto Add Project

on:
  issues:
    types:
      - opened
      - reopened

permissions:
  issues: write

jobs:
  add-to-project:
    runs-on: ubuntu-latest

    steps:
      - name: Add issue to v2 project
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const projectNumber = 1; // Replace with your project number
            const orgName = "jv-kune-kune"; // Replace with your organization name

            // Query to find the project ID
            const projectQuery = `
              query {
                organization(login: "${orgName}") {
                  projectV2(number: ${projectNumber}) {
                    id
                    title
                  }
                }
              }
            `;
            const projectResponse = await github.graphql(projectQuery);
            const projectId = projectResponse.organization.projectV2.id;

            // Mutation to add the issue to the project
            const addItemMutation = `
              mutation($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                  item {
                    id
                  }
                }
              }
            `;
            await github.graphql(addItemMutation, {
              projectId: projectId,
              contentId: context.payload.issue.node_id,
            });

            console.log(`Issue successfully added to project: ${projectResponse.organization.projectV2.title}`);
