name: Add Start Date to Issues

on:
  issues:
    types: [opened]

jobs:
  add-start-date:
    runs-on: ubuntu-latest
    steps:
      - name: Add Start Date to Project Item
        uses: actions/github-script@v6
        with:
          script: |
            const projectId = "PVT_kwDOC5OT-c4Av7Na"; // Your Project ID
            const startDateFieldId = "PVTF_lADOC5OT-c4Av7NazgmRpsQ"; // Field ID for Start Date
            const issueId = context.payload.issue.node_id; // Node ID of the created issue

            // Fetch project items to locate the issue
            const { node: project } = await octokit.graphql(`
              query($projectId: ID!) {
                node(id: $projectId) {
                  ... on ProjectV2 {
                    items(first: 100) {
                      nodes {
                        id
                        content {
                          ... on Issue {
                            id
                          }
                        }
                      }
                    }
                  }
                }
              }
            `, { projectId });

            const projectItem = project.items.nodes.find(item => item.content?.id === issueId);

            if (!projectItem) {
              console.log("Issue is not part of the project. Exiting...");
              return;
            }

            // Add today's date to the Start Date field
            const today = new Date().toISOString().split("T")[0]; // Format: YYYY-MM-DD
            await octokit.graphql(`
              mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $value: String!) {
                updateProjectV2ItemFieldValue(input: {
                  projectId: $projectId,
                  itemId: $itemId,
                  fieldId: $fieldId,
                  value: { text: $value }
                }) {
                  projectV2Item {
                    id
                  }
                }
              }
            `, {
              projectId,
              itemId: projectItem.id,
              fieldId: startDateFieldId,
              value: today,
            });

            console.log(`Start Date added to issue: ${context.payload.issue.title}`);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
