name: Add Start Date to "In Progress" Issues

on:
  project:
    types: [updated, labeled, unlabeled, edited, reopened]
  project_card:
    types: [moved, edited]

jobs:
  set-start-date:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check if Status is "In Progress"
      - name: Check Status
        id: check-status
        uses: EndBug/project-fields@v2
        with:
          operation: get
          fields: Status
          github_token: ${{ secrets.PAT_SECRET }}
          project_url: https://github.com/orgs/jv-kune-kune/projects/1
        env:
          TARGET_STATUS: "In Progress"

      # Step 2: Set Start Date if Status is "In Progress"
      - name: Set Start Date
        if: ${{ steps.check-status.outputs.values == env.TARGET_STATUS }}
        uses: EndBug/project-fields@v2
        with:
          operation: set
          fields: Start date
          github_token: ${{ secrets.PAT_SECRET }}
          project_url: https://github.com/orgs/jv-kune-kune/projects/1
          values: ${{ github.event.project.updated_at }}
