name: Update Estimate Based on Size

on:
  issues:
    types: [labeled, unlabeled, edited]

jobs:
  set-estimate:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Get the Size and Estimate fields
      - name: Get Fields
        uses: EndBug/project-fields@v2
        with:
          operation: get
          fields: Size,Estimate # Fetch both fields
          github_token: ${{ secrets.PAT_SECRET }}
          project_url: https://github.com/orgs/jv-kune-kune/projects/5
        id: get-fields

      # Step 2: Set the Estimate field if it's blank and Size has a value
      - name: Set Estimate
        if: ${{ steps.get-fields.outputs.values != ',' }} # Run only if at least one field has a value
        uses: EndBug/project-fields@v2
        with:
          operation: set
          fields: Estimate
          github_token: ${{ secrets.PAT_SECRET }}
          project_url: https://github.com/orgs/jv-kune-kune/projects/5
          values: |
            ${{ steps.get-fields.outputs.values.split(',')[0] == 'XXS' && '0' ||
                 steps.get-fields.outputs.values.split(',')[0] == 'XS' && '1' ||
                 steps.get-fields.outputs.values.split(',')[0] == 'S' && '2' ||
                 steps.get-fields.outputs.values.split(',')[0] == 'M' && '3' ||
                 steps.get-fields.outputs.values.split(',')[0] == 'L' && '8' ||
                 steps.get-fields.outputs.values.split(',')[0] == 'XL' && '13' ||
                 steps.get-fields.outputs.values.split(',')[0] == 'XXL' && '21' ||
                 'Unknown' }}
