name: Update Estimate Based on Size

on:
  issues:
    types: [labeled, unlabeled, edited]

jobs:
  set-estimate:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Fetch the Size field
      - name: Get Size
        uses: EndBug/project-fields@v2
        with:
          operation: get
          fields: Size,Estimate # Fetch both fields
          github_token: ${{ secrets.PAT_SECRET }}
          project_url: https://github.com/orgs/jv-kune-kune/projects/5
        id: get-size

      # Step 2: Update Estimate based on Size if Estimate is blank
      - name: Set Estimate
        if: ${{ steps.get-size.outputs.values.split(',')[0] != '' && steps.get-size.outputs.values.split(',')[1] == '' }}
        uses: EndBug/project-fields@v2
        with:
          operation: set
          fields: Estimate
          github_token: ${{ secrets.PAT_SECRET }}
          project_url: https://github.com/orgs/jv-kune-kune/projects/5
          values: |
            ${{ steps.get-size.outputs.values.split(',')[0] == 'XXS' && 0 ||
                 steps.get-size.outputs.values.split(',')[0] == 'XS' && 1 ||
                 steps.get-size.outputs.values.split(',')[0] == 'S' && 2 ||
                 steps.get-size.outputs.values.split(',')[0] == 'M' && 3 ||
                 steps.get-size.outputs.values.split(',')[0] == 'L' && 8 ||
                 steps.get-size.outputs.values.split(',')[0] == 'XL' && 13 ||
                 steps.get-size.outputs.values.split(',')[0] == 'XXL' && 21 }}
