name: Add Start Date to Issues

on:
  workflow_run:
    workflows:
      - Auto Add Project
    types:
      - completed

jobs:
  set-start-date:
    runs-on: ubuntu-latest
    steps:
      - name: Set Start Date
        uses: EndBug/project-fields@v2
        with:
          operation: set
          fields: Start date
          github_token: ${{ secrets.PAT_SECRET }}
          project_url: https://github.com/orgs/jv-kune-kune/projects/1
          resource_url: ${{ github.event.workflow_run.outputs.resource_url }}
          values: ${{ github.event.workflow_run.head_commit.timestamp }}
