name: Update Estimate Based on Size

on:
  issues:
    types: [labeled, unlabeled, edited]
  project_card:
    types: [created, edited, moved]
  project:
    types: [updated]

jobs:
  set-estimate:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Fetch Size and Estimate Fields
      - name: Get Fields
        uses: EndBug/project-fields@v2
        with:
          operation: get
          fields: Size,Estimate
          github_token: ${{ secrets.PAT_SECRET }}
          project_url: https://github.com/orgs/jv-kune-kune/projects/5
        id: get-fields

      # Step 2: Set the Estimate field if it’s blank and Size has a value
      - name: Set Estimate
        if: ${{ steps.get-fields.outputs.values != ',' }} # Ensure at least one field has a value
        uses: EndBug/project-fields@v2
        with:
          operation: set
          fields: Estimate
          github_token: ${{ secrets.PAT_SECRET }}
          project_url: https://github.com/orgs/jv-kune-kune/projects/5
          values: |
            ${{ 
              steps.get-fields.outputs.values == 'XXS,' && '0' || 
              steps.get-fields.outputs.values == 'XS,' && '1' || 
              steps.get-fields.outputs.values == 'S,' && '2' || 
              steps.get-fields.outputs.values == 'M,' && '3' || 
              steps.get-fields.outputs.values == 'L,' && '8' || 
              steps.get-fields.outputs.values == 'XL,' && '13' || 
              steps.get-fields.outputs.values == 'XXL,' && '21' || 
              'Unknown' 
            }}
